import images from '../constants/images';
import icons from '../constants/icons';

const UserCartdata = [
  {
    id: 0,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 1,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 2,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 3,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 4,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 5,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 6,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 7,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
  {
    id: 8,
    name: 'Sanjit kumar',
    driver: 'Shivam Bus',
    time: '02:30 PM (3/4/2023)',
    image: images.person,
  },
];

const BusLocationCartdata = [
  {
    id: 0,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 1,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 2,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 3,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 4,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 5,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 6,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 7,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
  {
    id: 8,
    name: 'Sanjit kumar',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    icons: icons.i,
  },
];

const PersonPymentCartdata = [
  {
    id: 0,
    name: 'Sanjit kumar',
    driverid: '12356789',
    image: images.person,
    rupee: 1500,
    status: '4 Month',
  },
  {
    id: 1,
    name: 'Sanjit kumar',
    driverid: '12356789',
    image: images.person,
    rupee: 1580,
    status: '4 Month',
  },
  {
    id: 2,
    name: 'Sanjit kumar',
    driverid: '12356789',
    image: images.person,
    rupee: 1500,
    status: 'Reject',
  },
  {
    id: 3,
    name: 'Sanjit kumar',
    driverid: '12356789',
    image: images.person,
    rupee: 1800,
    status: '4 Month',
  },
  {
    id: 4,
    name: 'Sanjit kumar',
    driverid: '12356789',
    image: images.person,
    rupee: 1500,
    status: '4 Month',
  },
  {
    id: 5,
    name: 'Sanjit kumar',
    driverid: '12356789',
    image: images.person,
    rupee: 2500,
    status: 'Reject',
  },
  {
    id: 6,
    name: 'Sanjit kumar',
    driverid: '12356789',
    image: images.person,
    rupee: 1500,
    status: '4 Month',
  },
  {
    id: 7,
    name: 'Sanjit kumar',
    driverid: '12356789',
    image: images.person,
    rupee: 1500,
    status: '4 Month',
  },
  {
    id: 8,
    name: 'Sanjit kumar',
    driverid: '12356789',
    image: images.person,
    rupee: 1500,
    status: '4 Month',
  },
];

const BusIdCartdata = [
  {
    id: 0,
    name: 'Shivam Bus',
    driverlocation: 'Hazaribagh( Jharkhand)',
    image: images.blackbus,
    busNo: 'JH01E 6785',
    time: '12:30 - 2:30 PM',
  },
  {
    id: 1,
    name: 'Shivam Bus',
    driverlocation: 'Hazaribagh to Ranchi',
    image: images.blackbus,
    busNo: 'JH01E 6785',
    time: '12:30 - 2:30 PM',
  },
  {
    id: 2,
    name: 'Shivam Bus',
    driverlocation: 'Hazaribagh to Ranchi',
    image: images.blackbus,
    busNo: 'JH01E 6785',
    time: '12:30 - 2:30 PM',
  },
  {
    id: 3,
    name: 'Shivam Bus',
    driverlocation: 'Hazaribagh to Ranchi',
    image: images.blackbus,
    busNo: 'JH01E 6785',
    time: '12:30 - 2:30 PM',
  },
  {
    id: 4,
    name: 'Shivam Bus',
    driverlocation: 'Hazaribagh to Ranchi',
    image: images.blackbus,
    busNo: 'JH01E 6785',
    time: '12:30 - 2:30 PM',
  },
  {
    id: 5,
    name: 'Shivam Bus',
    driverlocation: 'Hazaribagh to Ranchi',
    image: images.blackbus,
    busNo: 'JH01E 6785',
    time: '12:30 - 2:30 PM',
  },
  {
    id: 6,
    name: 'Shivam Bus',
    driverlocation: 'Hazaribagh to Ranchi',
    image: images.blackbus,
    busNo: 'JH01E 6785',
    time: '12:30 - 2:30 PM',
  },
  {
    id: 7,
    name: 'Shivam Bus',
    driverlocation: 'Hazaribagh to Ranchi',
    image: images.blackbus,
    busNo: 'JH01E 6785',
    time: '12:30 - 2:30 PM',
  },
  {
    id: 8,
    name: 'Shivam Bus',
    driverlocation: 'Hazaribagh to Ranchi',
    image: images.blackbus,
    busNo: 'JH01E 6785',
    time: '12:30 - 2:30 PM',
  },
];

const AttendenceCartdata = [
  {
    id: 0,
    date: '01/3/2013',
    present: 'Present - Morning',
    absent: 'Absent - Evening',
  },
  {
    id: 1,
    date: '01/3/2013',
    present: 'Present - Morning ,Evening',
  },
  {
    id: 2,
    date: '01/3/2013',
    present: 'Present - Morning',
    absent: 'Absent - Evening',
  },
  {
    id: 3,
    date: '01/3/2013',
    present: 'Present - Morning',
    absent: 'Absent - Evening',
  },
  {
    id: 4,
    date: '01/3/2013',
    present: 'Present - Morning',
  },
  {
    id: 5,
    date: '01/3/2013',
    present: 'Present - Morning',
    absent: 'Absent - Evening',
  },
  {
    id: 6,
    date: '01/3/2013',
    absent: 'Absent - Morning ,afternoon',
  },
  {
    id: 7,
    date: '01/3/2013',
    present: 'Present - Morning',
    absent: 'Absent - Evening',
  },
  {
    id: 8,
    date: '01/3/2013',
    absent: 'Absent - Morning ',
  },
];

export default {
  UserCartdata,
  BusLocationCartdata,
  PersonPymentCartdata,
  BusIdCartdata,
  AttendenceCartdata,
};
